version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  checkoutEtTests:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Clone backend repository
          command: git clone https://github.com/mambarr/3w5-h25-L01-backend.git backend
      - run:
          name: Install dependencies
          command: |
            cd backend
            npm install
      - run:
          name: Run tests
          command: |
            cd backend
            npm test
      - persist_to_workspace:
          root: .
          paths:
            - backend

  integrationFrontend:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Clone frontend repository
          command: git clone https://github.com/mambarr/3w5-h25-L01-frontend.git frontend
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Build frontend
          command: |
            cd frontend
            npm run build
      - run:
          name: Move frontend build to backend
          command: |
            mkdir -p backend/public
            cp -r frontend/build/* backend/public/
      - persist_to_workspace:
          root: .
          paths:
            - backend

  deploiement:
    docker:
      - image: cimg/node:18.16
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check backend structure
          command: |
            cd backend
            ls -Rl

workflows:
  version: 2
  build-deploy:
    jobs:
      - checkoutEtTests
      - integrationFrontend:
          requires:
            - checkoutEtTests
      - deploiement:
          requires:
            - integrationFrontend
